Repository GlobalNomad-FE/FE, pull requests merged in 2024-06, with the labels that each got.

#95 [Feat] Experience 컴포넌트 수정
  app/my-reservations/mock.json
  app/my-reservations/page.tsx
  components/commons/Popups/ReviewModal/ReviewModal.tsx
  components/commons/card/Experience.tsx
Labels: PR대기중👀

#83 [Feat] 예약내역 페이지 UI
  app/reservationHistory/page.tsx
Labels: PR대기중👀

#85 [Feat] 80 feat signin 페이지 UI
  app/signIn/page.tsx
  components/commons/Input.tsx
Labels: PR대기중👀

#94 [Feat] 메인페이지-이달의인기체험 컴포넌트 UI
  app/page.tsx
  components/MainBody.tsx
  components/MonthBest.tsx
  components/commons/Button.tsx
  components/commons/Popups/BasePopup.tsx
  components/commons/Popups/ReviewModal/ReviewContent.tsx
  components/commons/Popups/ReviewModal/ReviewForm.tsx
  components/commons/Popups/ReviewModal/ReviewModal.tsx
  tailwind.config.ts
Labels: PR대기중👀

#100 [Feat] 메인페이지에 서치바 추가
  app/searchBarTest/page.tsx
  app/testPopup/page.tsx
  components/MainBody.tsx
  components/commons/Popups/ReviewModal/ReviewModal.tsx
  components/commons/SearchBar.tsx
Labels: PR대기중👀

#101 [Refator] : footer 수정
  components/commons/Footer.tsx
Labels: PR대기중👀

#103 [Feat] 리액트 쿼리 초기세팅
  apis/ReactQueryProviders.tsx
  app/layout.tsx
  package-lock.json
  package.json
Labels: PR대기중👀

#107 [Feat] MainPage - GetActivities api 연결
  apis/.keep
  apis/activities/keys.ts
  apis/activities/useGetActivities.ts
  apis/axios.js
  app/page.tsx
  components/MainBody/MainBody.tsx
  components/MainBody/MonthBest.tsx
  next.config.mjs
  package-lock.json
  package.json
  tsconfig.json
Labels: PR대기중👀

#104 [Feat] 회원가입 페이지 ui
  apis/auth/auth.ts
  apis/auth/auth.type.ts
  apis/axios.js
  apis/axios.ts
  app/signup/page.tsx
  components/commons/Input.tsx
  components/commons/LoginInput.tsx
  package-lock.json
  package.json
  tsconfig.json
  utils/user.ts
Labels: 작업중🔥

#112 [Feat] Api엔드포인트 정리
  apis/activities/@common/activities.ts
  apis/my-activities/@common/myActivites.ts
  utils/constants/API.ts
Labels: PR대기중👀

#109 [Feat] 인기체험 컴포넌트
  apis/activities/keys.ts
  apis/activities/useGetActivities.ts
  app/page.tsx
  components/MainBody/HotActivitesItems.tsx
  components/MainBody/HotActivities.tsx
  components/MainBody/HotActivitiesPagination.tsx
  components/MainBody/MainBody.tsx
  components/MainBody/MonthBest.tsx
  components/commons/Popups/ReviewModal/ReviewForm.tsx
  components/commons/gnb/gnb.tsx
  public/icons/Star.svg
  public/icons/empty-star.svg
  tailwind.config.ts
Labels: 헬프😥, 완료😎

#121 [Feat] 메인페이지 수정
  components/MainBody/AllActivities.tsx
  components/MainBody/HotActivities.tsx
  components/MainBody/MainBody.tsx
  components/MainBody/MonthBest.tsx
  components/commons/Button.tsx
Labels: PR대기중👀

#125 [Feat] 쿠키로 변경
  apis/axios.ts
  package-lock.json
  package.json
Labels: PR대기중👀

#126 [Feat] 로그인 페이지 수정
  app/layout.tsx
  app/signIn/page.tsx
  app/signup/page.tsx
  components/commons/Input.tsx
  components/commons/LoginInput.tsx
  context/Authcontext.tsx
Labels: PR대기중👀

#127 [Feat] 예약현황 캘린더 구현
  app/reservationHistory/page.tsx
  components/reservationHistory/Calendar.tsx
Labels: PR대기중👀

#132 [Feat] 텍스트 블랙 로그인 회원가입 페이지
  apis/auth/auth.ts
  app/login/page.tsx
  app/signup/page.tsx
  components/MainBody/MonthBest.tsx
  components/commons/gnb/gnb.tsx
  context/Authcontext.tsx
Labels: PR대기중👀

#110 [Feat] 체험 등록/수정 페이지
  apis/UploadImage.ts
  apis/activities/@common/activities.ts
  apis/my-activities/@common/myActivites.ts
  app/activities/page.tsx
  app/activities/register/[id]/page.tsx
  app/activities/register/page.tsx
  components/activitie/registerPage.tsx
  components/commons/DateInput.css
  components/commons/DatePickerInput.tsx
  components/commons/Selectbox.tsx
  components/input/AddressInput.tsx
  components/input/BannerImageInput.tsx
  components/input/BaseInput.tsx
  components/input/BioImageInput.tsx
  components/input/CategoryInput.tsx
  components/input/ImageInput.tsx
  components/input/PriceInput.tsx
  components/input/TextInput.tsx
  components/input/TimeInput.tsx
  package-lock.json
  package.json
  public/icons/ImageAdd.svg
  public/icons/calendar_mini.svg
  public/icons/file-close-btn.svg
  public/icons/time_minus.svg
  public/icons/time_plus.svg
  public/icons/물결.svg
  tailwind.config.ts
  types/.keep
  types/activitiesType.ts
Labels: PR대기중👀

#119 [Feat] 체험관리페이지 데이터연결
  apis/activities/useDeleteActivites.ts
  apis/activities/useGetActivities.ts
  apis/activities/useGetInfinityActivitiesList.ts
  apis/my-activities/@common/myActivites.ts
  app/activities/page.tsx
  components/activitie/Menu.tsx
  components/commons/card/Experience.tsx
  hooks/useIntersectionObserver.ts
Labels: PR대기중👀

#136 [Feat] 체험 클릭시 상세페이지로 이동
  components/MainBody/AllActivities/AllActivities.tsx
  components/MainBody/AllActivities/AllActivitiesFilter.tsx
  components/MainBody/AllActivities/AllActivitiesItems.tsx
  components/MainBody/AllActivities/Categories.tsx
  components/MainBody/AllActivities/CategoryLists.tsx
  components/MainBody/HotActivities/HotActivities.tsx
  components/MainBody/HotActivities/HotActivitiesItems.tsx
  components/MainBody/HotActivities/HotActivitiesPagination.tsx
  components/MainBody/MainBody.tsx
Labels: PR대기중👀

#137 [Feat] 이벤트 막는거 수정, 필터 글자색 수정
  app/activities/page.tsx
  components/activitie/Menu.tsx
  components/commons/FilterDropdown.tsx
  components/commons/Popups/BasePopupTwoBtns.tsx
  components/commons/Popups/ReviewModal/ReviewModal.tsx
Labels: PR대기중👀

#139 [Feat] userID 쿠키에서 받아올 수 있도록 설정
  app/login/page.tsx
  app/signup/page.tsx
  components/commons/LoginInput.tsx
  context/Authcontext.tsx
Labels: PR대기중👀

#140 [Feat] 체험상세페이지 데이터 연동
  apis/activities/@common/activities.ts
  apis/activities/mutaion/useDeleteActivites.ts
  apis/activities/mutaion/usePostActivityReservation.ts
  apis/activities/useGetActivitesReviews.ts
  apis/activities/useGetActivitiesDetail.ts
  app/activities/[id]/page.tsx
  app/activities/detail/page.tsx
  app/activities/mock.json
  app/activities/page.tsx
  app/layout.tsx
  app/searchBarTest/mock.json
  app/testFilterDropdown/page.tsx
  app/testFloatingBox/page.tsx
  app/testMenuBar/page.tsx
  app/testPopup/page.tsx
  app/testPopup2/page.tsx
  app/testSeung/layout.tsx
  app/testSeung/page.tsx
  components/ReviewTable.tsx
  components/activitie/Map.tsx
  components/activitie/Menu.tsx
  components/activitie/Review.tsx
  components/activitie/activitieTitile/ActivitieTitle.tsx
  components/activitie/registerPage.tsx
  components/commons/calendar/Calendar.css
  components/commons/calendar/Calendar.tsx
  components/commons/gnb/gnb.tsx
  components/input/AddressInput.tsx
  components/reservationWidget/Calendar/PopupCalendar.tsx
  components/reservationWidget/Calendar/TabletCalendar.tsx
  components/reservationWidget/Container/DesktopReservationWidgetContainer.tsx
  components/reservationWidget/Container/MobileReservationWidgetContainer.tsx
  components/reservationWidget/Container/TabletReservationWidgetContainer.tsx
  components/reservationWidget/common/ParticipantCount.tsx
  components/reservationWidget/common/TimeSelector.tsx
  components/reservationWidget/common/TotalPrice.tsx
  components/reservationWidget/lib/Calendar.provider.tsx
  components/reservationWidget/lib/Calendar.types.tsx
  components/reviewmock.json
  components/tests/EmailExist.tsx
  components/tests/ReservationCompleted.tsx
Labels: PR대기중👀

#144 [Feat] 알림 모달 생성
  apis/my-notifications/keys.tsx
  apis/my-notifications/useDeleteMyNotification.tsx
  apis/my-notifications/useGetMyNotifications.tsx
  app/testNotifications/page.tsx
  components/activitie/Menu.tsx
  components/commons/card/Experience.tsx
  components/commons/myNotifications/MyNotifications.tsx
  components/commons/myNotifications/Notifications.tsx
  public/icons/notification.svg
  public/icons/notifications-close.svg
  utils/formatDateDiff.ts
Labels: PR대기중👀

#146 [Feat] 리뷰모달 api연결
  apis/my-reservations/usePostReview.ts
  components/MainBody/AllActivities/AllActivities.tsx
  components/commons/Popups/BasePopup.tsx
  components/commons/Popups/ReviewModal/ReviewContent.tsx
  components/commons/Popups/ReviewModal/ReviewForm.tsx
  components/commons/Popups/ReviewModal/ReviewModal.tsx
Labels: PR대기중👀

#149 [Feat] 캘린더에 chips 및 예약 존재 여부 아이콘 표시
  app/reservationHistory/page.tsx
  components/reservationHistory/Calendar.tsx
  components/reservationHistory/Chips.tsx
  public/icons/ellipse_blue.svg
  public/icons/ellipse_gray.svg
  types/activitiesReservationType.ts
Labels: PR대기중👀

#142 [Feat] 인스턴스에서 userID 넣기
  apis/axios.ts
  app/login/page.tsx
  app/signup/page.tsx
  components/commons/LoginInput.tsx
Labels: PR대기중👀

#156 [Feat] 체험상세 등록 수정 페이지 기능추가
  apis/ReactQueryProviders.tsx
  apis/activities/mutaion/useDeleteActivites.ts
  apis/activities/mutaion/usePostActivityReservation.ts
  apis/activities/useGetInfinityActivitiesList.ts
  app/activities/[id]/page.tsx
  app/activities/page.tsx
  app/layout.tsx
  app/my-reservations/page.tsx
  components/ReviewTable.tsx
  components/activitie/Map.tsx
  components/activitie/Menu.tsx
  components/activitie/Review.tsx
  components/activitie/activitieTitile/ActivitieTitle.tsx
  components/activitie/registerPage.tsx
  components/commons/Popups/BasePopup.tsx
  components/commons/SideNavigationMenu.tsx
  components/input/BannerImageInput.tsx
  components/input/BaseInput.tsx
  components/reservationWidget/Container/DesktopReservationWidgetContainer.tsx
  components/reservationWidget/Container/MobileReservationWidgetContainer.tsx
  components/reservationWidget/Container/TabletReservationWidgetContainer.tsx
  components/skeleton/MyActivitiyExperienceSkeleton.tsx
  components/skeleton/ReviewExperienceSkeleton.tsx
  package-lock.json
  package.json
Labels: PR대기중👀

#157 [Feat] 알림 모달 수정
  apis/my-notifications/useGetMyNotifications.tsx
  components/commons/myNotifications/MyNotifications.tsx
  components/commons/myNotifications/Notifications.tsx
  components/commons/myNotifications/NotificationsItem.tsx
  styles/globals.css
Labels: PR대기중👀

#161 [Feat] gnb 메뉴 dropdown 구현
  components/commons/dropdownMenu/DropdownMenu.tsx
  components/commons/gnb/gnb.tsx
  public/icons/logout-check.png
Labels: PR대기중👀

#147 [Feat] 내 정보 페이지
  apis/auth/auth.ts
  apis/user/editMyInfo.ts
  apis/user/getUserInfo.ts
  apis/user/uploadProfileImage.ts
  app/myprofile/page.tsx
  components/commons/SideNavigationMenu.tsx
  components/myProfile/InformationImage.tsx
  components/myProfile/MyPageForm.tsx
  components/myProfile/MyPageInputBox.tsx
  components/myProfile/MypageInputLabel.tsx
  components/myProfile/PageMenu.tsx
  components/myProfile/ProfileImage.tsx
  hooks/useUserProfile.ts
  libs/useUserStore.ts
  types/EditInformationErrorMessageType.ts
Labels: PR대기중👀

#158 [Feat] 예약 확인현황 캘린더 내 데이터 연결
  apis/my-activitie-reservation-status/keys.ts
  apis/my-activitie-reservation-status/useGetMyActivities.ts
  apis/my-activitie-reservation-status/useGetMyReservationStatus.ts
  apis/my-activitie-reservation-status/useGetReservationDashboard.ts
  apis/my-activitie-reservation-status/useGetReservedSchedule.ts
  apis/my-activitie-reservation-status/useGetReservedTime.ts
  app/reservationHistory/page.tsx
  components/commons/Popups/ReservationHistory/ReservationInfoModal.tsx
  components/reservationHistory/Calendar.tsx
  components/reservationHistory/Chips.tsx
  components/reservationHistory/ReservationInfo.tsx
  components/reservationHistory/SelectBox.tsx
Labels: PR대기중👀

#162 [Feat] Experience 컴포넌트 분리, 후기 작성 버튼 disabled 추가, 예약 내역 페이지 스켈레톤 적용
  app/activities/page.tsx
  app/my-reservations/page.tsx
  components/commons/Button.tsx
  components/commons/Popups/ReviewModal/ReviewModal.tsx
  components/commons/card/ActivitiesExperience.tsx
  components/commons/card/ExperienceType.ts
  components/commons/card/ReservationsExperience.tsx
  components/skeleton/ReviewExperienceSkeleton.tsx
Labels: PR대기중👀

#165 [Feat] GNB 연결
  components/commons/gnb/gnb.tsx
  types/myInfo.ts
Labels: PR대기중👀

#172 [Feat] 메인페이지 리뷰반영 수정
  components/MainBody/AllActivities/AllActivitiesItems.tsx
  components/MainBody/AllActivities/CategoryLists.tsx
  components/MainBody/HotActivities/HotActivities.tsx
  hooks/useDragScroll.ts
Labels: PR대기중👀

#169 [Feat] 사이드메뉴바 프로필이미지수정
  apis/user/uploadProfileImage.ts
  apis/user/useGetProfile.ts
  app/activities/page.tsx
  app/my-reservations/page.tsx
  app/myprofile/page.tsx
  components/commons/SideNavigationMenu.tsx
  components/commons/gnb/gnb.tsx
  components/myProfile/MyPageForm.tsx
  components/myProfile/MyPageInputBox.tsx
  components/myProfile/ProfileImage.tsx
  hooks/useUserProfile.ts
Labels: PR대기중👀

#176 [Feat] register 페이지 css 수정
  apis/user/uploadProfileImage.ts
  app/login/page.tsx
  app/signup/page.tsx
  components/activitie/registerPage.tsx
  components/commons/DatePickerInput.tsx
  components/commons/Input.tsx
  components/commons/Selectbox.tsx
  components/input/TimeInput.tsx
  components/myProfile/InformationImage.tsx
  hooks/useIntersectionObserver.ts
  hooks/useUserProfile.ts
Labels: PR대기중👀

#175 [Feat] 예약현황 내 잔여작업
  apis/my-activity-reservation-status/keys.ts
  apis/my-activity-reservation-status/useGetMyActivities.ts
  apis/my-activity-reservation-status/useGetMyReservationStatus.ts
  apis/my-activity-reservation-status/useGetReservationDashboard.ts
  apis/my-activity-reservation-status/useGetReservedSchedule.ts
  apis/my-activity-reservation-status/useGetReservedTime.ts
  apis/my-activity-reservation-status/usePatchReservationRequest.ts
  app/reservationHistory/page.tsx
  components/commons/Popups/ReservationHistory/ReservationInfoModal.tsx
  components/reservationHistory/Calendar.tsx
  components/reservationHistory/Chips.tsx
  components/reservationHistory/ReservationInfo.tsx
Labels: PR대기중👀

#179 [Feat] Gnb 고치는중
  app/login/page.tsx
  components/commons/avatar/avatar.tsx
  components/commons/gnb/gnb.tsx
  hooks/useUserProfile.ts
Labels: PR대기중👀

#177 [Feat] 넥스트 미들웨어 설정
  app/_middleware.ts
  app/login/page.tsx
  components/commons/gnb/gnb.tsx
  hooks/useUserProfile.ts
Labels: 헬프😥, 작업중🔥

#183 [Feat] 체험상세페이지 캘린더 수정
  apis/activities/mutation/useDeleteActivity.ts
  apis/activities/mutation/usePostActivityReservation.ts
  apis/activities/useGetActivitiesDetail.ts
  apis/activities/useGetActivitiesReviews.ts
  apis/activities/useGetInfinityActivitiesList.ts
  apis/my-activities/@common/myActivity.ts
  app/activities/[id]/page.tsx
  app/activities/page.tsx
  app/activities/register/[id]/page.tsx
  app/activities/register/page.tsx
  components/ReviewTable.tsx
  components/activity/ActivityBio.tsx
  components/activity/Map.tsx
  components/activity/Menu.tsx
  components/activity/RegisterPage.tsx
  components/activity/Review.tsx
  components/activity/activitieType.tsx
  components/activity/activityTitle/ActivityTitle.tsx
  components/commons/SelectBox.tsx
  components/commons/card/ActivitiesExperience.tsx
  components/input/AddressInput.tsx
  components/input/CategoryInput.tsx
  components/input/TimeInput.tsx
  components/reservationWidget/Calendar/PopupCalendar.tsx
  components/reservationWidget/Calendar/TabletCalendar.tsx
  components/reservationWidget/Container/DesktopReservationWidgetContainer.tsx
  components/reservationWidget/Container/MobileReservationWidgetContainer.tsx
  components/reservationWidget/Container/TabletReservationWidgetContainer.tsx
  components/reservationWidget/common/ReservationWidgetWrapper.tsx
  components/reservationWidget/common/TimeSelector.tsx
  components/reservationWidget/lib/Calendar.provider.tsx
  components/reservationWidget/lib/Calendar.types.tsx
  components/skeleton/MyActivityExperienceSkeleton.tsx
Labels: PR대기중👀

#184 [Feat] gnb, DropdownMenu, 알림 창 수정
  apis/my-notifications/useGetMyNotifications.tsx
  components/commons/avatar/avatar.tsx
  components/commons/dropdownMenu/DropdownMenu.tsx
  components/commons/gnb/gnb.tsx
Labels: PR대기중👀

#185 [Feat] 예약현황페이지 오타 및 css수정
  app/reservationHistory/page.tsx
  components/commons/Popups/ReservationHistory/ReservationInfoModal.tsx
  components/reservationHistory/Calendar.tsx
  components/reservationHistory/SelectBox.tsx
  types/myActivitiesType.ts
Labels: PR대기중👀

#190 [Feat] 체험수정 페이지 수정
  components/activity/RegisterPage.tsx
  components/input/BannerImageInput.tsx
Labels: PR대기중👀

#194 [Feat] 예약 현황 내 캘린더 UI 반응형 수정
  app/reservationHistory/page.tsx
  components/reservationHistory/Calendar.tsx
  components/reservationHistory/SelectBox.tsx
Labels: PR대기중👀

#195 [Feat] DropdownMenu 위치, gnb 간격 수정, test 파일 삭제
  app/testNotifications/page.tsx
  components/commons/dropdownMenu/DropdownMenu.tsx
  components/commons/gnb/gnb.tsx
Labels: PR대기중👀

#196 [Feat] 넥스트 미들웨어
  _middleware.tsx
  middleware.ts
Labels: PR대기중👀

#197 [Feat] 체험 제목 길면 짜르기
  components/MainBody/AllActivities/AllActivitiesItems.tsx
Labels: PR대기중👀

#200 [Feat] 메인화면 사이즈오류 수정
  components/MainBody/AllActivities/AllActivities.tsx
  components/MainBody/AllActivities/AllActivitiesItems.tsx
Labels: 버그수정🚨

#199 [Feat] 예약 내역 모달 내 승인, 거절 시 캘린더와 모달의 데이터를 다시 불러오도록 수정
  apis/my-activity-reservation-status/keys.ts
  apis/my-activity-reservation-status/usePatchReservationRequest.ts
  components/reservationHistory/ReservationInfo.tsx
Labels: PR대기중👀
